import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Components/Providers";
import NextTopLoader from 'nextjs-toploader';
import { cookieToInitialState } from "wagmi";
import { config } from "./config";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader
        color="#8B075E"
        />
        <Provider >
        {children}
        </Provider>
        </body>
    </html>
  );
}
