"use client"
import Image from "next/image";
import Link from "next/link";
import Navbar from "./Components/Navbar";
import { IoMdCheckmarkCircleOutline } from "react-icons/io";
import Footer from "./Components/Footer";
import { IoSunnySharp } from "react-icons/io5";
import { FaChevronLeft, FaChevronRight } from "react-icons/fa";
import {motion,AnimatePresence, useAnimate} from "framer-motion";
import { useEffect, useState } from "react";
export default function Home() {
  const [scope,animate] = useAnimate();
  const [scope1,animate1] = useAnimate();
  const [started,setStarted] = useState<boolean|null>(null);
  useEffect( 
    ()=>{
      function animation(){
        setStarted(started=>true);
        animate(scope.current,{rotate:[0,120,280,360]},{duration:6})
        setTimeout(
          ()=>{
            animate1(scope1.current,{x:"15rem"},{duration:2,ease:"easeInOut"})
      
          },6000
        )
        setTimeout(
          ()=>{
          
            animate1(scope1.current,{rotate:[0,-110,-180]},{duration:2,ease:"easeInOut"})
            
          },8000
        )
        setTimeout(
          ()=>{
  
            animate1(scope1.current,{x:0},{duration:2,ease:"easeInOut"})
          },10000
        )
        setStarted(started=>false);
      }
      animation()
    },[started]);

  const arrowVariant = {
    initial:{
      y:0,
      rotate:"-180deg"
    },
    animate:{
      y:"10rem",
      rotate:"180deg",
      transition:{
        duration:2
      }
    }
  }
  return (
    <div className="w-[100vw] overflow-hidden h-full flex flex-col gap-20 items-center justify-center bg-[#1c044d] relative">
      <div className="absolute rounded-full z-10 bg-[#9F0861] w-[150vh] blur-[300px] h-[250vh] -top-20 -left-96"></div>
      <div className="absolute rounded-full z-5 bg-[#856FF7] w-[150vh] blur-[300px] h-[300vh]  -right-60 "></div>
      <Image
        src="/Images/binarymeshbg.png"
        width={500}
        height={500}
        alt="bg"
        className="absolute z-0 top-[15.5rem] sc1:top-[15.5rem]  w-[80rem] sc1:w-[80rem] sc1:h-[36rem] h-[35rem]"
      />
      <Navbar />
      <div className="w-full h-full flex flex-col items-center relative z-20 justify-center gap-28 h-full">
        <div className="flex flex-col justify-between items-center gap-6 w-[50%] text-center">
          <div className="text-[0.9rem]">Welcome To Megadrome</div>
          <div className="text-4xl font-bold mx-3">
            The central trading and liquidity marketplace on
            <span className="font-bold text-violet-500 italic mx-2">MONAD</span>
          </div>
        </div>
        <div className="w-[40%] text-md text-center mt-10">
          Megadrome Finance is a next-generation AMM that combines the best of
          Curve, Convex and Uniswap, designed to serve as Optimism's central
          liquidity hub. Velodrome NFTs vote on token emissions and receive
          incentives and fees generated by the protocol.
        </div>
        <div className="w-[80%] grid  grid-cols-3 gap-4  text-lg">
          <div className="w-full rounded-xl border border-[#836EF9] flex justify-between px-6 py-6">
            <span> Stable & Volatile Trading for Low Fees </span>
            <IoMdCheckmarkCircleOutline size={20}/>
          </div>
          <div className="w-full rounded-xl border border-[#836EF9] flex justify-between px-6 py-6">
            <span> Stable & Volatile Trading for Low Fees </span>
            <IoMdCheckmarkCircleOutline size={20}/>
          </div>
          <div className="w-full rounded-xl border border-[#836EF9] flex justify-between px-6 py-6">
            <span> Stable & Volatile Trading for Low Fees </span>
            <IoMdCheckmarkCircleOutline size={20}/>
          </div>
          <div className="w-full rounded-xl border border-[#836EF9] flex justify-between px-6 py-6">
            <span> Stable & Volatile Trading for Low Fees </span>
            <IoMdCheckmarkCircleOutline size={20}/>
          </div>
          <div className="w-full rounded-xl border border-[#836EF9] flex justify-between px-6 py-6">
            <span> Stable & Volatile Trading for Low Fees </span>
            <IoMdCheckmarkCircleOutline size={20}/>
          </div>
          <div className="w-full rounded-xl border border-[#836EF9] flex justify-between px-6 py-6">
            <span> Stable & Volatile Trading for Low Fees </span>
            <IoMdCheckmarkCircleOutline size={20}/>
          </div>
        </div>
        <div className="w-[80%] h-full py-10 flex mb-32 ">
          <div className="w-[50%] flex flex-col gap-2">
            <span className="text-slate-100 text-[1.3rem]">How it works</span>
            <span className="text-3xl font-bold w-[65%] leading-30 text-white">
              Designed to reward participants that enable the sustainable growth
              of the protocol.
            </span>
          </div>
          <div className=" w-[40%] flex items-end relative top-40 right-20">
          <div ref={scope} className="border-[4px] border-[#5E0457] z-10 w-[15rem] h-[15rem] rounded-full absolute">
          <div  className="bg-red-700 w-6 h-6 z-30 p-2 rounded-full text-white absolute left-[5rem] -bottom-3 flex items-center justify-center"><FaChevronLeft/>
            </div>
          </div>
          <div ref={scope1} className=" border-[4px] border-transparent z-10 w-[15rem] h-[15rem] rounded-full absolute">
          <div id="prop" className="bg-red-700 w-6 h-6 z-20 p-2 rounded-full text-white absolute left-[5rem] -bottom-3 flex items-center justify-center"><FaChevronRight/>
            </div>
          </div>
          
            <div className="border-[4px] border-[#480B5D] w-[30rem] h-[15rem] font-bold rounded-full absolute ">
              <div className="bg-white text-[0.7rem] text-black rounded-xl z-50 w-[25%] bottom-[1rem] flex items-center justify-center relative left-12 bottom-[0.5rem] py-2">veMEGA VOTERS</div>
              <div className="bg-white text-[0.7rem] text-black rounded-xl z-40 w-[15%] top-[11.5rem] flex items-center justify-center relative left-[5rem] py-2">LPs</div>
              <div className="bg-white text-[0.7rem] text-black rounded-xl z-50 w-[25%]  flex items-center justify-center relative left-[25rem] px-8 py-1">PROTOCOLS</div>
              <div className="bg-white text-[0.7rem] text-black rounded-xl z-50 w-[15%] top-[2rem] flex items-center justify-center relative right-[2rem] px-4 py-1">TRADERS</div>
              <div className="flex absolute w-fit items-center z-50 gap-1 top-[4rem] -left-7"> 
                <div className="text-[0.7rem]">FEES</div>
                <div className="bg-white rounded-full w-3 h-3"></div>
              </div>
              <div className="flex absolute w-fit items-center gap-1 z-50 top-[12rem] -left-12"> 
                <div className="text-[0.7rem]">Low Slippage</div>
                <div className="bg-white rounded-full w-3 h-3"></div>
              </div>
              <div className="flex absolute w-fit items-center gap-1 z-50 top-[0.8rem] -right-5"> 
                <div className="bg-white rounded-full w-3 h-3"></div>
                <div className="text-[0.7rem]">Incentives</div>
              </div>
              <div className="flex absolute w-fit items-center gap-1 top-[8rem] -right-[3.5rem]"> 
                <div className="bg-white rounded-full w-3 h-3"></div>
                <div className="text-[0.7rem]">Liquidity</div>
              </div>
              <div className="flex absolute w-fit items-center gap-1 z-50 top-[3rem] left-[13rem]"> 
                <div className="bg-white rounded-full w-3 h-3"></div>
                <div className="text-[0.7rem]">Mega Emissions</div>
              </div>
            </div>
            <div className="border-[4px] border-[#5E0457] w-[15rem] h-[15rem] z-5 rounded-full absolute"></div>
          </div>
        </div>
        <div className="w-[80%] h-full px-4 grid grid-cols-4 gap-3 ">
          <div className="py-4 px-6 rounded-lg w-full h-[25rem] bg-[#210053] overflow-hidden relative gap-2 flex flex-col items-start justify-start">
            <span className="text-white">Traders</span>
            <span className="text-gray-400 text-sm">
              Swap tokens with minimal slippage and pay some of the lowest fees
              to MEGA lockers.
            </span>
            <div className="w-full h-full relative">
            <Image src="/Images/binarymesh2.png" width={1000} height={1000} alt="mesh" className="absolute left-10 top-[14.8rem] " style={{transform:"scale(8)"}}/>
            </div>
          </div>
          <div className="rounded-lg w-full relative gap-4  shadow-sm shadow-slate-500 flex flex-col items-start justify-start">
            <div className="absolute h-full w-full bg-black rounded-lg opacity-5 "></div>
            <div className="absolute h-[25rem] flex py-6 px-6 flex-col overflow-hidden relative gap-2 w-full z-10">
              <span className="text-white">Liquidity Providers</span>
              <span className="text-gray-200 text-sm">
                Deposit the tokens used for trading on Megadrome and receive
                MEGO emissions as rewards.
              </span>
              <div className="w-full h-full relative">
            <Image src="/Images/binarymesh2.png" width={1000} height={1000} alt="mesh" className="absolute right-[14rem] sc1:right-[16rem] sc1:top-[14.5rem] top-[13rem] " style={{transform:"scale(8)"}}/>
            </div>
            </div>
          </div>
          <div className="rounded-lg w-full relative gap-4 shadow-sm shadow-slate-500 flex flex-col items-start justify-start">
            <div className="absolute h-full w-full bg-black rounded-lg opacity-5"></div>
            <div className="absolute h-[25rem] flex py-6 px-6 flex-col overflow-hidden gap-2 w-full z-10">
              <span className="text-white">Protocols</span>
              <span className="text-gray-200 text-sm">
                Offer incentives to veMEGA voters to attract votes / MEGA
                emissions to their pools, allowing them to build liquidity at a
                low cost.
              </span>
              <div className="w-full h-full relative">
            <Image src="/Images/binarymesh3.png" width={500} height={500} alt="mesh" className="absolute bottom-[6rem] left-[9rem]" style={{transform:"scale(5) rotate(300deg)"}}/>
            </div>
            </div>
          </div>
          <div className="rounded-lg w-full  relative gap-4 shadow-sm shadow-slate-500 flex flex-col items-start justify-start">
            <div className="absolute h-full w-full bg-black rounded-lg opacity-5"></div>
            <div className="absolute h-[25rem] flex py-6 px-6 overflow-hidden flex-col gap-2 w-full z-10">
              <span className="text-white">vMEGA Voters</span>
              <span className="text-gray-200 text-sm">
                Vote on which pools will earn MEGA emissions and receive 100% of
                incentives and fees for the pools they vote for. Any MEGA holder
                can lock their tokens to convert to veMEGA.
              </span>
              <div className="w-full h-full relative">
            <Image src="/Images/binarymesh3.png" width={500} height={500} alt="mesh" className="absolute bottom-[4rem] right-[6.5rem] sc1:right-[7.5rem]" style={{transform:"scale(5) rotate(300deg)"}}/>
            </div>
            </div>
          </div>
        </div>
        <div className="w-[70%] text-3xl font-bold flex justify-between gap-20 items-center">
          <div className="flex flex-col  items-center justify-center">
          <span>$150.06M</span>
          <span className="text-[0.7rem]">Total Value Locked</span>
          </div>
          
          <div className="flex flex-col items-center justify-center">
          <span>$347.63M</span>
          <span className="text-[0.7rem]">Monthly Volume</span>
          </div>
          <div className="flex flex-col items-center justify-center">
          <span>$4.36M</span>
          <span className="text-[0.6rem]">MONTHLY FEES</span>
          </div>
          <div className="flex flex-col items-center justify-center">
          <span>97.16K</span>
          <span className="text-[0.7rem]">MONTHLY USERS</span>
          </div>
        </div>

        <div className="h-full py-12 w-full bg-black flex flex-col gap-12 items-center justify-center">
          <div className="w-[60%] flex justify-between">
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
            <svg
              width="49"
              height="49"
              viewBox="0 0 49 49"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g opacity="0.7" clip-path="url(#clip0_204_122)">
                <g clip-path="url(#clip1_204_122)">
                  <g clip-path="url(#clip2_204_122)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M24.5298 47.6101C37.2323 47.6101 47.5298 37.3126 47.5298 24.6101C47.5298 11.9076 37.2323 1.61011 24.5298 1.61011C11.8273 1.61011 1.52979 11.9076 1.52979 24.6101C1.52979 37.3126 11.8273 47.6101 24.5298 47.6101ZM24.5298 48.6101C37.7846 48.6101 48.5298 37.8649 48.5298 24.6101C48.5298 11.3553 37.7846 0.610107 24.5298 0.610107C11.275 0.610107 0.529785 11.3553 0.529785 24.6101C0.529785 37.8649 11.275 48.6101 24.5298 48.6101Z"
                      fill="#394150"
                    />
                    <path
                      d="M17.5266 30.9749C16.2779 31.0281 15.0456 30.6742 14.0155 29.9665C13.5705 29.6266 13.2149 29.1834 12.9797 28.6752C12.7444 28.167 12.6365 27.6092 12.6652 27.0499C12.6707 26.724 12.7008 26.399 12.7553 26.0777C12.9114 25.2121 13.1334 24.1738 13.4214 22.9628C14.2377 19.6618 16.3442 18.0113 19.7409 18.0113C20.5922 17.9974 21.4376 18.1567 22.2255 18.4795C22.9249 18.7536 23.5266 19.2301 23.9539 19.8479C24.3847 20.4845 24.6049 21.2403 24.5834 22.0087C24.5772 22.3285 24.5471 22.6475 24.4933 22.9628C24.3131 24.0311 24.0971 25.0694 23.8453 26.0777C23.4256 27.722 22.6994 28.9523 21.6668 29.7686C20.6352 30.5728 19.2551 30.9749 17.5266 30.9749ZM17.7788 28.3821C18.4024 28.3993 19.0108 28.188 19.4895 27.788C20.0185 27.3082 20.3784 26.6704 20.5156 25.9695C20.7918 24.8416 21.0016 23.8574 21.1451 23.0167C21.1934 22.7614 21.2175 22.5022 21.2171 22.2424C21.2171 21.15 20.647 20.6039 19.5068 20.6041C18.8781 20.589 18.2649 20.7998 17.7784 21.1982C17.2591 21.6831 16.9062 22.3195 16.77 23.0167C16.5539 23.8209 16.3379 24.8052 16.122 25.9695C16.0731 26.2186 16.049 26.4719 16.05 26.7257C16.05 27.83 16.6263 28.3821 17.7788 28.3821Z"
                      fill="#394150"
                    />
                    <path
                      d="M25.4124 30.795C25.3552 30.7984 25.298 30.7888 25.245 30.767C25.192 30.7452 25.1446 30.7118 25.1063 30.6691C25.0464 30.5724 25.027 30.4559 25.0524 30.3449L27.537 18.6416C27.559 18.5125 27.6293 18.3965 27.7337 18.3174C27.8302 18.2378 27.9509 18.1934 28.076 18.1915H32.8654C33.993 18.1362 35.1107 18.425 36.0704 19.0197C36.4649 19.2781 36.7853 19.6349 37 20.0548C37.2147 20.4748 37.3163 20.9434 37.2948 21.4146C37.293 21.7297 37.2568 22.0437 37.1866 22.351C36.988 23.5641 36.3385 24.6574 35.3681 25.412C34.4679 26.0722 33.2315 26.4023 31.6591 26.4023H29.2288L28.4006 30.3453C28.3786 30.4745 28.3082 30.5904 28.2039 30.6695C28.1075 30.7491 27.9869 30.7935 27.862 30.7954L25.4124 30.795ZM31.7862 23.9169C32.2579 23.9273 32.72 23.7818 33.1007 23.503C33.4924 23.2153 33.7621 22.7914 33.8569 22.3148C33.8903 22.1366 33.9083 21.9559 33.9108 21.7746C33.921 21.6281 33.8989 21.4812 33.846 21.3443C33.7931 21.2073 33.7107 21.0837 33.6047 20.9822C33.3042 20.7603 32.9322 20.6577 32.5605 20.6942H30.4001L29.7159 23.9169H31.7862Z"
                      fill="#394150"
                    />
                  </g>
                </g>
              </g>
              <defs>
                <clipPath id="clip0_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip1_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
                <clipPath id="clip2_204_122">
                  <rect
                    width="48"
                    height="48"
                    fill="white"
                    transform="translate(0.529785 0.610107)"
                  />
                </clipPath>
              </defs>
            </svg>
          </div>
          <div className="w-[60%] flex justify-center py-3 items-center text-[0.5rem] text-slate-400 border-y border-y-slate-900">
          Data and metrics are openly available on Token Terminal and Dune
          </div>
          <div className="w-full h-fit  flex flex-col justify-center items-center">
            <Image src='/Images/rocket.png' width={500} height={200} className="w-[25rem] h-[25rem]" alt="rocket"/>
            <button className="text-md text-slate-300 border boder-slate-900 rounded-xl px-2 py-2 relative bottom-32">Onboarding Guide</button>
            <span className="w-[30%] flex justify-center text-center relative bottom-24 text-4xl font-bold">Looking to get started with Megadrome Finance?</span>
          </div>
          <div className='flex items-center w-full justify-center lg:flex'>
      <div id='footer' className='h-fit flex flex-col pt-4 lg:pt-44 pb-12 px-20  w-full items-center justify-center gap-3'>
        <div className='flex justify-between items-center w-full'>
            <div className='flex text-[0.7rem] flex-col lg:flex-row gap-10 w-full'>
                <span className='text-white'>Articles</span>
                <span className='text-white'> Support</span>
                <div className='flex gap-6'>
                    <Image src="/Images/logos/x.png" width={20} height={20} alt='x'/>
                    <Image src="/Images/logos/logo2.png" width={20} height={20} alt='x'/>
                    <Image src="/Images/logos/discord.png" width={20} height={20} alt='x'/>
                    <Image src="/Images/logos/logo4.png" width={20} height={20} alt='x'/>
                    <Image src="/Images/logos/github.png" width={20} height={20} alt='x'/>
                </div>
                
            </div>
            <div>
                <IoSunnySharp size={20} />
            </div>
            <div></div>
        </div>
        <div className='w-full'>
            <hr className='w-full border border-slate-900 '/>
        </div>
        <div className='flex justify-between w-full items-center '>
            <div className='flex flex-col lg:flex-row gap-10 text-[0.7rem] text-white'>
                <span>Documentation</span>
                <span>Security</span>
                <span>BrandKit</span>
                <span>Tokens</span>
            </div>
            <div className='px-2 py-1 flex text-[0.7rem] text-slate-400 h-fit border border-slate-700 items-center gap-2 rounded-md'>
                <span>Mirrors</span>
                <FaChevronLeft/>
            </div>
        </div>
        {/* <div className='flex justify-between w-full'></div> */}
        </div>
    </div>
        </div>
      </div>
    </div>
  );
}
